### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by utbuiquoc** [jeffshee/gnome-ext-hanabi#11]
I installed (image below)
![image](https://user-images.githubusercontent.com/86715840/183596326-fc0dee65-6c23-4730-9986-e0a6ad7a2060.png)
When restart, only transparent window show up.

**Comment by utbuiquoc** [comment]
![image](https://user-images.githubusercontent.com/86715840/183596940-96dff8b6-8ce4-49b4-af59-0b309be63ca3.png)

**Comment by jeffshee** [comment]
Hi @utbuiquoc, thanks for reporting.

Please check #10, probably the same issue. It's fixed now.
If not, please reopen this issue =)

**Comment by utbuiquoc** [comment]
[Screencast from 09-08-2022 17:19:53.webm](https://user-images.githubusercontent.com/86715840/183625230-6ee6e2d5-e8f4-4323-8123-e86b9df53865.webm)
Thanks for replay, issue is fixed but video still not showed.
